-- Clause Check sample data for the SQL and BigQuery days (generated by a script; do not edit by hand).
-- Six customers, ten contracts, one row per clause review, eval runs and tool calls.
CREATE TABLE customers (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  country TEXT NOT NULL,          -- ISO code: SE, NO, EE, US, FI, NL
  plan TEXT NOT NULL,             -- starter / pro / enterprise
  signed_up TEXT NOT NULL         -- date, YYYY-MM-DD
);
CREATE TABLE contracts (
  id INTEGER PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(id),
  title TEXT NOT NULL,
  uploaded_at TEXT NOT NULL,      -- timestamp, YYYY-MM-DD HH:MM:SS (UTC)
  pages INTEGER NOT NULL,
  status TEXT NOT NULL            -- reviewed / in_review / failed
);
CREATE TABLE reviews (
  id INTEGER PRIMARY KEY,
  contract_id INTEGER NOT NULL REFERENCES contracts(id),
  clause_id TEXT NOT NULL,        -- '8.1', '10.1' ... (text, so '10.1' < '8.1' when sorted as text)
  heading TEXT NOT NULL,
  topic TEXT NOT NULL,
  verdict TEXT,                   -- accept / flag / redline; NULL when the review failed
  risk TEXT,                      -- low / medium / high; NULL when the review failed
  rule_ids TEXT,                  -- JSON array as text, e.g. '["PB-01", "PB-02"]'
  model TEXT NOT NULL,            -- deepseek-v4-flash / deepseek-v4-pro
  prompt_version TEXT NOT NULL,   -- v1 / v2
  prompt_tokens INTEGER NOT NULL,
  completion_tokens INTEGER NOT NULL,
  cache_hit_tokens INTEGER NOT NULL,
  latency_ms INTEGER NOT NULL,
  cost_usd REAL NOT NULL,         -- at the peak list price per model (2026-09)
  error TEXT,                     -- NULL unless the review failed
  created_at TEXT NOT NULL        -- timestamp, YYYY-MM-DD HH:MM:SS (UTC)
);
CREATE TABLE evals (
  id INTEGER PRIMARY KEY,
  case_id TEXT NOT NULL,
  prompt_version TEXT NOT NULL,
  run INTEGER NOT NULL,           -- 1..3
  expected TEXT NOT NULL,         -- the verdict the case expects
  verdict TEXT NOT NULL,          -- what the model answered
  passed INTEGER NOT NULL,        -- 1 / 0
  latency_ms INTEGER NOT NULL,
  created_at TEXT NOT NULL
);
CREATE TABLE tool_calls (
  id INTEGER PRIMARY KEY,
  review_id INTEGER NOT NULL REFERENCES reviews(id),
  step INTEGER NOT NULL,
  tool TEXT NOT NULL,             -- lookup_playbook / get_clause / mark_for_review
  args TEXT NOT NULL,             -- JSON object as text
  ok INTEGER NOT NULL,            -- 1 / 0
  latency_ms INTEGER NOT NULL
);
INSERT INTO customers VALUES (1, 'Nordlys AB', 'SE', 'enterprise', '2025-11-03');
INSERT INTO customers VALUES (2, 'Fjord Health AS', 'NO', 'enterprise', '2026-01-15');
INSERT INTO customers VALUES (3, 'Baltic Freight OU', 'EE', 'pro', '2026-03-02');
INSERT INTO customers VALUES (4, 'CloudNotes Inc', 'US', 'pro', '2026-04-20');
INSERT INTO customers VALUES (5, 'Helsinki Legal Oy', 'FI', 'starter', '2026-06-11');
INSERT INTO customers VALUES (6, 'Amsterdam Data BV', 'NL', 'starter', '2026-08-30');
INSERT INTO contracts VALUES (101, 1, 'CloudNotes SaaS Agreement', '2026-08-03 09:12:00', 12, 'reviewed');
INSERT INTO contracts VALUES (102, 1, 'Data Processing Addendum', '2026-08-10 14:30:00', 6, 'reviewed');
INSERT INTO contracts VALUES (103, 2, 'Hospital Software License', '2026-08-12 08:05:00', 24, 'reviewed');
INSERT INTO contracts VALUES (104, 2, 'Support Services Order', '2026-08-25 16:40:00', 4, 'reviewed');
INSERT INTO contracts VALUES (105, 3, 'Freight Platform Terms', '2026-08-28 11:00:00', 18, 'reviewed');
INSERT INTO contracts VALUES (106, 3, 'Warehouse API License', '2026-09-02 10:20:00', 9, 'in_review');
INSERT INTO contracts VALUES (107, 4, 'Reseller Agreement', '2026-09-05 13:15:00', 15, 'reviewed');
INSERT INTO contracts VALUES (108, 4, 'Mutual NDA', '2026-09-08 09:45:00', 3, 'reviewed');
INSERT INTO contracts VALUES (109, 5, 'Legal Research Subscription', '2026-09-12 15:05:00', 7, 'failed');
INSERT INTO contracts VALUES (110, 1, 'Renewal Amendment', '2026-09-15 10:00:00', 2, 'reviewed');
INSERT INTO reviews VALUES (1001, 101, '3.1', 'Fees', 'payment', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v1', 1943, 152, 0, 1296, 0.000765, NULL, '2026-08-03 09:14:04');
INSERT INTO reviews VALUES (1002, 101, '3.5', 'Suspension Without Notice', 'payment', 'flag', 'medium', '["PB-05"]', 'deepseek-v4-flash', 'v1', 2487, 137, 1939, 1693, 0.00034, NULL, '2026-08-03 09:14:08');
INSERT INTO reviews VALUES (1003, 101, '4.2', 'Automatic Renewal', 'auto_renewal', 'redline', 'medium', '["PB-04"]', 'deepseek-v4-flash', 'v1', 2617, 110, 1831, 2149, 0.000379, NULL, '2026-08-03 09:14:13');
INSERT INTO reviews VALUES (1004, 101, '6.1', 'Confidential Information', 'confidentiality', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v1', 2075, 171, 1141, 3662, 0.000492, NULL, '2026-08-03 09:14:19');
INSERT INTO reviews VALUES (1005, 101, '8.1', 'Cap on Liability', 'liability_cap', 'redline', 'high', '["PB-01", "PB-02"]', 'deepseek-v4-flash', 'v1', 2103, 102, 1640, 3563, 0.000271, NULL, '2026-08-03 09:14:25');
INSERT INTO reviews VALUES (1006, 101, '8.2', 'Exclusions from the Cap', 'liability_cap', 'flag', 'high', '["PB-02"]', 'deepseek-v4-flash', 'v1', 1881, 169, 1316, 2926, 0.00038, NULL, '2026-08-03 09:14:30');
INSERT INTO reviews VALUES (1007, 101, '10.1', 'Data Location', 'data_processing', 'accept', 'low', '["PB-07"]', 'deepseek-v4-flash', 'v1', 2054, 118, 1273, 3587, 0.000384, NULL, '2026-08-03 09:14:36');
INSERT INTO reviews VALUES (1008, 101, '9.1', 'Warranties', 'warranty', 'accept', 'low', '["PB-00"]', 'deepseek-v4-flash', 'v1', 2403, 173, 1321, 3708, 0.00054, NULL, '2026-08-03 09:14:42');
INSERT INTO reviews VALUES (1009, 101, '9.2', 'Disclaimer', 'warranty', 'flag', 'low', '["PB-00"]', 'deepseek-v4-flash', 'v1', 2202, 137, 1541, 2810, 0.000372, NULL, '2026-08-03 09:14:47');
INSERT INTO reviews VALUES (1010, 101, '11.2', 'Termination for Convenience', 'termination', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v1', 2119, 161, 1313, 2308, 0.000443, NULL, '2026-08-03 09:14:52');
INSERT INTO reviews VALUES (1011, 101, '14.1', 'Governing Law', 'governing_law', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v1', 2483, 200, 1539, 1401, 0.000532, NULL, '2026-08-03 09:14:56');
INSERT INTO reviews VALUES (1012, 101, '15.4', 'Notices', 'other', 'accept', 'low', '["PB-00"]', 'deepseek-v4-flash', 'v1', 2210, 197, 1215, 2230, 0.000542, NULL, '2026-08-03 09:15:01');
INSERT INTO reviews VALUES (1013, 102, '10.1', 'Data Location', 'data_processing', 'redline', 'high', '["PB-07"]', 'deepseek-v4-flash', 'v1', 2378, 162, 0, 3318, 0.000908, NULL, '2026-08-10 14:32:06');
INSERT INTO reviews VALUES (1014, 102, '10.3', 'Sub-processors', 'data_processing', 'flag', 'medium', '["PB-08"]', 'deepseek-v4-flash', 'v1', 2279, 137, 1777, 2458, 0.000326, NULL, '2026-08-10 14:32:11');
INSERT INTO reviews VALUES (1015, 102, '6.1', 'Confidential Information', 'confidentiality', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v1', 2376, 191, 1663, 3586, 0.000453, NULL, '2026-08-10 14:32:17');
INSERT INTO reviews VALUES (1016, 102, '8.1', 'Cap on Liability', 'liability_cap', 'accept', 'low', '["PB-01"]', 'deepseek-v4-flash', 'v1', 1885, 237, 1319, 3639, 0.000462, NULL, '2026-08-10 14:32:23');
INSERT INTO reviews VALUES (1017, 102, '14.1', 'Governing Law', 'governing_law', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v1', 2374, 225, 1851, 2950, 0.000438, NULL, '2026-08-10 14:32:28');
INSERT INTO reviews VALUES (1018, 103, '3.1', 'Fees', 'payment', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v1', 1890, 113, 0, 3017, 0.000703, NULL, '2026-08-12 08:07:06');
INSERT INTO reviews VALUES (1019, 103, '3.4', 'Late Payment', 'payment', 'flag', 'medium', '["PB-05"]', 'deepseek-v4-flash', 'v1', 2224, 200, 1223, 2849, 0.000548, NULL, '2026-08-12 08:07:11');
INSERT INTO reviews VALUES (1020, 103, '4.2', 'Renewal Term', 'auto_renewal', 'accept', 'low', '["PB-04"]', 'deepseek-v4-flash', 'v1', 1919, 221, 1189, 2177, 0.000491, NULL, '2026-08-12 08:07:16');
INSERT INTO reviews VALUES (1021, 103, '6.2', 'Duration of Confidentiality', 'confidentiality', 'redline', 'medium', '["PB-06"]', 'deepseek-v4-flash', 'v1', 2270, 114, 1248, 3079, 0.000451, NULL, '2026-08-12 08:07:22');
INSERT INTO reviews VALUES (1022, 103, '8.1', 'Cap on Liability', 'liability_cap', 'redline', 'high', '["PB-01", "PB-02"]', 'deepseek-v4-pro', 'v1', 2118, 497, 1313, 9438, 0.003088, NULL, '2026-08-12 08:07:34');
INSERT INTO reviews VALUES (1023, 103, '8.2', 'Exclusions from the Cap', 'liability_cap', 'flag', 'high', '["PB-02"]', 'deepseek-v4-pro', 'v1', 2245, 535, 1571, 8544, 0.003077, NULL, '2026-08-12 08:07:45');
INSERT INTO reviews VALUES (1024, 103, '10.1', 'Data Location', 'data_processing', 'accept', 'low', '["PB-07"]', 'deepseek-v4-flash', 'v1', 2225, 203, 1379, 1351, 0.000506, NULL, '2026-08-12 08:07:49');
INSERT INTO reviews VALUES (1025, 103, '10.3', 'Sub-processors', 'data_processing', 'flag', 'medium', '["PB-08"]', 'deepseek-v4-flash', 'v1', 1924, 141, 1192, 1613, 0.000396, NULL, '2026-08-12 08:07:53');
INSERT INTO reviews VALUES (1026, 103, '9.1', 'Warranties', 'warranty', 'accept', 'low', '["PB-00"]', 'deepseek-v4-flash', 'v1', 1913, 195, 1186, 1699, 0.000459, NULL, '2026-08-12 08:07:57');
INSERT INTO reviews VALUES (1027, 103, '11.3', 'Termination by Supplier', 'termination', 'flag', 'medium', '["PB-09"]', 'deepseek-v4-flash', 'v1', 2707, 240, 1678, 3086, 0.000607, NULL, '2026-08-12 08:08:03');
INSERT INTO reviews VALUES (1028, 103, '14.1', 'Governing Law', 'governing_law', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v1', 1844, 217, 1014, 3346, 0.000515, NULL, '2026-08-12 08:08:09');
INSERT INTO reviews VALUES (1029, 103, '15.4', 'Notices', 'other', 'accept', 'low', '["PB-00"]', 'deepseek-v4-flash', 'v1', 1998, 211, 1398, 3150, 0.000442, NULL, '2026-08-12 08:08:15');
INSERT INTO reviews VALUES (1030, 104, '3.1', 'Fees', 'payment', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v2', 2544, 106, 0, 2649, 0.00089, NULL, '2026-08-25 16:42:05');
INSERT INTO reviews VALUES (1031, 104, '4.2', 'Automatic Renewal', 'auto_renewal', 'redline', 'medium', '["PB-04"]', 'deepseek-v4-flash', 'v2', 2662, 245, 1464, 2260, 0.000662, NULL, '2026-08-25 16:42:10');
INSERT INTO reviews VALUES (1032, 104, '8.1', 'Cap on Liability', 'liability_cap', 'accept', 'low', '["PB-01"]', 'deepseek-v4-flash', 'v2', 1982, 137, 1090, 3248, 0.000439, NULL, '2026-08-25 16:42:16');
INSERT INTO reviews VALUES (1033, 104, '11.2', 'Termination for Convenience', 'termination', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v2', 2158, 177, 1186, 1598, 0.000511, NULL, '2026-08-25 16:42:20');
INSERT INTO reviews VALUES (1034, 104, '15.4', 'Notices', 'other', 'accept', 'low', '["PB-00"]', 'deepseek-v4-flash', 'v2', 2035, 158, 1587, 1926, 0.000334, NULL, '2026-08-25 16:42:24');
INSERT INTO reviews VALUES (1035, 105, '3.1', 'Fees', 'payment', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v2', 1842, 109, 0, 1980, 0.000683, NULL, '2026-08-28 11:02:04');
INSERT INTO reviews VALUES (1036, 105, '3.5', 'Suspension Without Notice', 'payment', 'flag', 'medium', '["PB-05"]', 'deepseek-v4-flash', 'v2', 2220, 145, 1221, 3388, 0.000481, NULL, '2026-08-28 11:02:10');
INSERT INTO reviews VALUES (1037, 105, '4.2', 'Renewal Term', 'auto_renewal', 'accept', 'low', '["PB-04"]', 'deepseek-v4-flash', 'v2', 2121, 107, 1654, 1939, 0.000278, NULL, '2026-08-28 11:02:14');
INSERT INTO reviews VALUES (1038, 105, '6.1', 'Confidential Information', 'confidentiality', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v2', 1823, 114, 1276, 3579, 0.000309, NULL, '2026-08-28 11:02:20');
INSERT INTO reviews VALUES (1039, 105, '8.1', 'Cap on Liability', 'liability_cap', 'accept', 'low', '["PB-01"]', 'deepseek-v4-flash', 'v2', 2341, 193, 1451, 2609, 0.000507, NULL, '2026-08-28 11:02:25');
INSERT INTO reviews VALUES (1040, 105, '10.1', 'Data Location', 'data_processing', 'redline', 'high', '["PB-07"]', 'deepseek-v4-flash', 'v2', 1980, 99, 1227, 2173, 0.000352, NULL, '2026-08-28 11:02:30');
INSERT INTO reviews VALUES (1041, 105, '9.1', 'Warranties', 'warranty', 'accept', 'low', '["PB-00"]', 'deepseek-v4-flash', 'v2', 2246, 142, 1235, 2032, 0.000481, NULL, '2026-08-28 11:02:35');
INSERT INTO reviews VALUES (1042, 105, '9.2', 'Disclaimer', 'warranty', 'flag', 'low', '["PB-00"]', 'deepseek-v4-flash', 'v2', 2631, 187, 2052, 1401, 0.00041, NULL, '2026-08-28 11:02:39');
INSERT INTO reviews VALUES (1043, 105, '11.3', 'Termination by Supplier', 'termination', 'flag', 'medium', '["PB-09"]', 'deepseek-v4-flash', 'v2', 2628, 208, 2049, 2239, 0.000436, NULL, '2026-08-28 11:02:44');
INSERT INTO reviews VALUES (1044, 105, '14.1', 'Governing Law', 'governing_law', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v2', 2054, 118, 1273, 2290, 0.000384, NULL, '2026-08-28 11:02:49');
INSERT INTO reviews VALUES (1045, 106, '3.1', 'Fees', 'payment', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v2', 1866, 234, 0, 1846, 0.000841, NULL, '2026-09-02 10:22:04');
INSERT INTO reviews VALUES (1046, 106, '8.1', 'Cap on Liability', 'liability_cap', 'redline', 'high', '["PB-01", "PB-02"]', 'deepseek-v4-flash', 'v2', 2102, 104, 1471, 1322, 0.000323, NULL, '2026-09-02 10:22:08');
INSERT INTO reviews VALUES (1047, 106, '10.1', 'Data Location', 'data_processing', NULL, NULL, NULL, 'deepseek-v4-flash', 'v2', 2370, 0, 1469, 2346, 0.000279, 'ValidationError: risk_level ''critical'' is not allowed', '2026-09-02 10:22:13');
INSERT INTO reviews VALUES (1048, 107, '3.4', 'Late Payment', 'payment', 'flag', 'medium', '["PB-05"]', 'deepseek-v4-flash', 'v2', 1903, 214, 0, 1322, 0.000828, NULL, '2026-09-05 13:17:04');
INSERT INTO reviews VALUES (1049, 107, '4.2', 'Automatic Renewal', 'auto_renewal', 'redline', 'medium', '["PB-04"]', 'deepseek-v4-flash', 'v2', 2143, 145, 1178, 3788, 0.000471, NULL, '2026-09-05 13:17:10');
INSERT INTO reviews VALUES (1050, 107, '6.2', 'Duration of Confidentiality', 'confidentiality', 'redline', 'medium', '["PB-06"]', 'deepseek-v4-flash', 'v2', 2691, 149, 2098, 3014, 0.000369, NULL, '2026-09-05 13:17:16');
INSERT INTO reviews VALUES (1051, 107, '8.2', 'Exclusions from the Cap', 'liability_cap', 'flag', 'high', '["PB-02"]', 'deepseek-v4-pro', 'v2', 2407, 525, 1877, 8654, 0.002861, NULL, '2026-09-05 13:17:27');
INSERT INTO reviews VALUES (1052, 107, '10.1', 'Data Location', 'data_processing', 'accept', 'low', '["PB-07"]', 'deepseek-v4-flash', 'v2', 2210, 92, 1547, 2755, 0.000319, NULL, '2026-09-05 13:17:32');
INSERT INTO reviews VALUES (1053, 107, '11.2', 'Termination for Convenience', 'termination', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v2', 2422, 134, 1332, 3743, 0.000496, NULL, '2026-09-05 13:17:38');
INSERT INTO reviews VALUES (1054, 107, '14.1', 'Governing Law', 'governing_law', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v2', 2364, 161, 1654, 3300, 0.000416, NULL, '2026-09-05 13:17:44');
INSERT INTO reviews VALUES (1055, 107, '15.4', 'Notices', 'other', 'accept', 'low', '["PB-00"]', 'deepseek-v4-flash', 'v2', 2129, 156, 1319, 2337, 0.000438, NULL, '2026-09-05 13:17:49');
INSERT INTO reviews VALUES (1056, 108, '6.1', 'Confidential Information', 'confidentiality', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v2', 2338, 130, 0, 2625, 0.000857, NULL, '2026-09-08 09:47:05');
INSERT INTO reviews VALUES (1057, 108, '6.2', 'Duration of Confidentiality', 'confidentiality', 'redline', 'medium', '["PB-06"]', 'deepseek-v4-flash', 'v2', 2718, 217, 2120, 1756, 0.000453, NULL, '2026-09-08 09:47:09');
INSERT INTO reviews VALUES (1058, 108, '14.1', 'Governing Law', 'governing_law', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v2', 2351, 217, 1457, 2861, 0.000537, NULL, '2026-09-08 09:47:14');
INSERT INTO reviews VALUES (1059, 108, '15.4', 'Notices', 'other', 'accept', 'low', '["PB-00"]', 'deepseek-v4-flash', 'v2', 2211, 189, 1216, 3356, 0.000533, NULL, '2026-09-08 09:47:20');
INSERT INTO reviews VALUES (1060, 109, '3.1', 'Fees', 'payment', 'accept', 'low', '[]', 'deepseek-v4-flash', 'v2', 1999, 131, 0, 1550, 0.000757, NULL, '2026-09-12 15:07:04');
INSERT INTO reviews VALUES (1061, 109, '8.1', 'Cap on Liability', 'liability_cap', NULL, NULL, NULL, 'deepseek-v4-flash', 'v2', 1911, 0, 1490, 2166, 0.000135, '429 Rate limit reached after 3 attempts', '2026-09-12 15:07:09');
INSERT INTO reviews VALUES (1062, 110, '4.2', 'Automatic Renewal', 'auto_renewal', 'redline', 'medium', '["PB-04"]', 'deepseek-v4-flash', 'v2', 1915, 222, 0, 3348, 0.000841, NULL, '2026-09-15 10:02:06');
INSERT INTO reviews VALUES (1063, 110, '15.4', 'Notices', 'other', 'accept', 'low', '["PB-00"]', 'deepseek-v4-flash', 'v2', 2730, 140, 1692, 3484, 0.00049, NULL, '2026-09-15 10:02:12');
INSERT INTO reviews VALUES (1064, 103, '8.1', 'Cap on Liability', 'liability_cap', 'flag', 'high', '["PB-01"]', 'deepseek-v4-flash', 'v2', 2410, 180, 1700, 2150, 0.000439, NULL, '2026-09-18 11:02:13');
INSERT INTO reviews VALUES (1065, 109, '8.1', 'Cap on Liability', 'liability_cap', 'accept', 'low', '["PB-01"]', 'deepseek-v4-flash', 'v2', 2105, 140, 1400, 1890, 0.000388, NULL, '2026-09-19 09:30:41');
INSERT INTO evals VALUES (1, 'unlimited-liability', 'v1', 1, 'redline', 'redline', 1, 2241, '2026-09-10 09:00:11');
INSERT INTO evals VALUES (2, 'unlimited-liability', 'v1', 2, 'redline', 'redline', 1, 1501, '2026-09-10 09:00:22');
INSERT INTO evals VALUES (3, 'unlimited-liability', 'v1', 3, 'redline', 'redline', 1, 2157, '2026-09-10 09:00:29');
INSERT INTO evals VALUES (4, 'liability-carveout-xref', 'v1', 1, 'flag', 'flag', 1, 1732, '2026-09-10 09:00:40');
INSERT INTO evals VALUES (5, 'liability-carveout-xref', 'v1', 2, 'flag', 'flag', 1, 2905, '2026-09-10 09:00:47');
INSERT INTO evals VALUES (6, 'liability-carveout-xref', 'v1', 3, 'flag', 'redline', 0, 3152, '2026-09-10 09:00:54');
INSERT INTO evals VALUES (7, 'data-any-country', 'v1', 1, 'redline', 'redline', 1, 1701, '2026-09-10 09:01:05');
INSERT INTO evals VALUES (8, 'data-any-country', 'v1', 2, 'redline', 'redline', 1, 1636, '2026-09-10 09:01:13');
INSERT INTO evals VALUES (9, 'data-any-country', 'v1', 3, 'redline', 'redline', 1, 2027, '2026-09-10 09:01:24');
INSERT INTO evals VALUES (10, 'renewal-24-months', 'v1', 1, 'redline', 'redline', 1, 2120, '2026-09-10 09:01:33');
INSERT INTO evals VALUES (11, 'renewal-24-months', 'v1', 2, 'redline', 'redline', 1, 3362, '2026-09-10 09:01:43');
INSERT INTO evals VALUES (12, 'renewal-24-months', 'v1', 3, 'redline', 'redline', 1, 2677, '2026-09-10 09:01:54');
INSERT INTO evals VALUES (13, 'as-is-mutual', 'v1', 1, 'accept', 'accept', 1, 2576, '2026-09-10 09:02:05');
INSERT INTO evals VALUES (14, 'as-is-mutual', 'v1', 2, 'accept', 'flag', 0, 2180, '2026-09-10 09:02:14');
INSERT INTO evals VALUES (15, 'as-is-mutual', 'v1', 3, 'accept', 'flag', 0, 3487, '2026-09-10 09:02:21');
INSERT INTO evals VALUES (16, 'service-levels-boilerplate', 'v1', 1, 'accept', 'accept', 1, 3346, '2026-09-10 09:02:29');
INSERT INTO evals VALUES (17, 'service-levels-boilerplate', 'v1', 2, 'accept', 'flag', 0, 3140, '2026-09-10 09:02:40');
INSERT INTO evals VALUES (18, 'service-levels-boilerplate', 'v1', 3, 'accept', 'flag', 0, 2835, '2026-09-10 09:02:49');
INSERT INTO evals VALUES (19, 'notices-boilerplate', 'v1', 1, 'accept', 'accept', 1, 2890, '2026-09-10 09:02:58');
INSERT INTO evals VALUES (20, 'notices-boilerplate', 'v1', 2, 'accept', 'accept', 1, 1506, '2026-09-10 09:03:06');
INSERT INTO evals VALUES (21, 'notices-boilerplate', 'v1', 3, 'accept', 'flag', 0, 1996, '2026-09-10 09:03:13');
INSERT INTO evals VALUES (22, 'suspension-without-notice', 'v1', 1, 'flag', 'flag', 1, 1741, '2026-09-10 09:03:22');
INSERT INTO evals VALUES (23, 'suspension-without-notice', 'v1', 2, 'flag', 'flag', 1, 2111, '2026-09-10 09:03:29');
INSERT INTO evals VALUES (24, 'suspension-without-notice', 'v1', 3, 'flag', 'flag', 1, 3418, '2026-09-10 09:03:38');
INSERT INTO evals VALUES (25, 'unlimited-liability', 'v2', 1, 'redline', 'redline', 1, 1730, '2026-09-17 09:00:07');
INSERT INTO evals VALUES (26, 'unlimited-liability', 'v2', 2, 'redline', 'redline', 1, 3357, '2026-09-17 09:00:17');
INSERT INTO evals VALUES (27, 'unlimited-liability', 'v2', 3, 'redline', 'redline', 1, 3188, '2026-09-17 09:00:26');
INSERT INTO evals VALUES (28, 'liability-carveout-xref', 'v2', 1, 'flag', 'flag', 1, 3381, '2026-09-17 09:00:34');
INSERT INTO evals VALUES (29, 'liability-carveout-xref', 'v2', 2, 'flag', 'flag', 1, 1827, '2026-09-17 09:00:44');
INSERT INTO evals VALUES (30, 'liability-carveout-xref', 'v2', 3, 'flag', 'flag', 1, 2082, '2026-09-17 09:00:54');
INSERT INTO evals VALUES (31, 'data-any-country', 'v2', 1, 'redline', 'redline', 1, 2307, '2026-09-17 09:01:03');
INSERT INTO evals VALUES (32, 'data-any-country', 'v2', 2, 'redline', 'redline', 1, 1786, '2026-09-17 09:01:13');
INSERT INTO evals VALUES (33, 'data-any-country', 'v2', 3, 'redline', 'redline', 1, 2128, '2026-09-17 09:01:21');
INSERT INTO evals VALUES (34, 'renewal-24-months', 'v2', 1, 'redline', 'redline', 1, 2608, '2026-09-17 09:01:29');
INSERT INTO evals VALUES (35, 'renewal-24-months', 'v2', 2, 'redline', 'redline', 1, 3298, '2026-09-17 09:01:40');
INSERT INTO evals VALUES (36, 'renewal-24-months', 'v2', 3, 'redline', 'flag', 0, 3464, '2026-09-17 09:01:49');
INSERT INTO evals VALUES (37, 'as-is-mutual', 'v2', 1, 'accept', 'accept', 1, 3350, '2026-09-17 09:01:56');
INSERT INTO evals VALUES (38, 'as-is-mutual', 'v2', 2, 'accept', 'accept', 1, 2450, '2026-09-17 09:02:05');
INSERT INTO evals VALUES (39, 'as-is-mutual', 'v2', 3, 'accept', 'flag', 0, 2552, '2026-09-17 09:02:16');
INSERT INTO evals VALUES (40, 'service-levels-boilerplate', 'v2', 1, 'accept', 'accept', 1, 1945, '2026-09-17 09:02:23');
INSERT INTO evals VALUES (41, 'service-levels-boilerplate', 'v2', 2, 'accept', 'accept', 1, 1762, '2026-09-17 09:02:31');
INSERT INTO evals VALUES (42, 'service-levels-boilerplate', 'v2', 3, 'accept', 'accept', 1, 3039, '2026-09-17 09:02:40');
INSERT INTO evals VALUES (43, 'notices-boilerplate', 'v2', 1, 'accept', 'accept', 1, 2639, '2026-09-17 09:02:48');
INSERT INTO evals VALUES (44, 'notices-boilerplate', 'v2', 2, 'accept', 'accept', 1, 2410, '2026-09-17 09:02:55');
INSERT INTO evals VALUES (45, 'notices-boilerplate', 'v2', 3, 'accept', 'accept', 1, 2026, '2026-09-17 09:03:03');
INSERT INTO evals VALUES (46, 'suspension-without-notice', 'v2', 1, 'flag', 'flag', 1, 3179, '2026-09-17 09:03:11');
INSERT INTO evals VALUES (47, 'suspension-without-notice', 'v2', 2, 'flag', 'flag', 1, 1732, '2026-09-17 09:03:22');
INSERT INTO evals VALUES (48, 'suspension-without-notice', 'v2', 3, 'flag', 'flag', 1, 2484, '2026-09-17 09:03:31');
INSERT INTO tool_calls VALUES (1, 1001, 1, 'lookup_playbook', '{"topic": "payment"}', 1, 15);
INSERT INTO tool_calls VALUES (2, 1002, 1, 'lookup_playbook', '{"topic": "payment"}', 1, 37);
INSERT INTO tool_calls VALUES (3, 1003, 1, 'lookup_playbook', '{"topic": "auto_renewal"}', 1, 29);
INSERT INTO tool_calls VALUES (4, 1004, 1, 'lookup_playbook', '{"topic": "confidentiality"}', 1, 9);
INSERT INTO tool_calls VALUES (5, 1005, 1, 'lookup_playbook', '{"topic": "liability_cap"}', 1, 26);
INSERT INTO tool_calls VALUES (6, 1006, 1, 'lookup_playbook', '{"topic": "liability_cap"}', 1, 18);
INSERT INTO tool_calls VALUES (7, 1006, 2, 'get_clause', '{"clause_id": "12"}', 1, 29);
INSERT INTO tool_calls VALUES (8, 1007, 1, 'lookup_playbook', '{"topic": "data_processing"}', 1, 13);
INSERT INTO tool_calls VALUES (9, 1008, 1, 'lookup_playbook', '{"topic": "warranty"}', 1, 42);
INSERT INTO tool_calls VALUES (10, 1009, 1, 'lookup_playbook', '{"topic": "warranty"}', 1, 34);
INSERT INTO tool_calls VALUES (11, 1009, 2, 'mark_for_review', '{"reason": "mutual AS IS disclaimer"}', 1, 32);
INSERT INTO tool_calls VALUES (12, 1010, 1, 'lookup_playbook', '{"topic": "termination"}', 1, 39);
INSERT INTO tool_calls VALUES (13, 1011, 1, 'lookup_playbook', '{"topic": "governing_law"}', 1, 8);
INSERT INTO tool_calls VALUES (14, 1012, 1, 'lookup_playbook', '{"topic": "other"}', 1, 30);
INSERT INTO tool_calls VALUES (15, 1018, 1, 'lookup_playbook', '{"topic": "payment"}', 1, 34);
INSERT INTO tool_calls VALUES (16, 1019, 1, 'lookup_playbook', '{"topic": "payment"}', 1, 33);
INSERT INTO tool_calls VALUES (17, 1020, 1, 'lookup_playbook', '{"topic": "auto_renewal"}', 1, 28);
INSERT INTO tool_calls VALUES (18, 1021, 1, 'lookup_playbook', '{"topic": "confidentiality"}', 1, 18);
INSERT INTO tool_calls VALUES (19, 1022, 1, 'lookup_playbook', '{"topic": "liability_cap"}', 1, 23);
INSERT INTO tool_calls VALUES (20, 1022, 2, 'get_clause', '{"clause_id": "99"}', 0, 5);
INSERT INTO tool_calls VALUES (21, 1023, 1, 'lookup_playbook', '{"topic": "liability_cap"}', 1, 10);
INSERT INTO tool_calls VALUES (22, 1023, 2, 'get_clause', '{"clause_id": "12"}', 1, 12);
INSERT INTO tool_calls VALUES (23, 1024, 1, 'lookup_playbook', '{"topic": "data_processing"}', 1, 14);
INSERT INTO tool_calls VALUES (24, 1025, 1, 'lookup_playbook', '{"topic": "data_processing"}', 1, 34);
INSERT INTO tool_calls VALUES (25, 1026, 1, 'lookup_playbook', '{"topic": "warranty"}', 1, 10);
INSERT INTO tool_calls VALUES (26, 1027, 1, 'lookup_playbook', '{"topic": "termination"}', 1, 18);
INSERT INTO tool_calls VALUES (27, 1028, 1, 'lookup_playbook', '{"topic": "governing_law"}', 1, 41);
INSERT INTO tool_calls VALUES (28, 1029, 1, 'lookup_playbook', '{"topic": "other"}', 1, 35);
INSERT INTO tool_calls VALUES (29, 1048, 1, 'lookup_playbook', '{"topic": "payment"}', 1, 22);
INSERT INTO tool_calls VALUES (30, 1049, 1, 'lookup_playbook', '{"topic": "auto_renewal"}', 1, 13);
INSERT INTO tool_calls VALUES (31, 1050, 1, 'lookup_playbook', '{"topic": "confidentiality"}', 1, 6);
INSERT INTO tool_calls VALUES (32, 1051, 1, 'lookup_playbook', '{"topic": "liability_cap"}', 1, 15);
INSERT INTO tool_calls VALUES (33, 1051, 2, 'get_clause', '{"clause_id": "12"}', 1, 42);
INSERT INTO tool_calls VALUES (34, 1052, 1, 'lookup_playbook', '{"topic": "data_processing"}', 1, 24);
INSERT INTO tool_calls VALUES (35, 1053, 1, 'lookup_playbook', '{"topic": "termination"}', 1, 39);
INSERT INTO tool_calls VALUES (36, 1054, 1, 'lookup_playbook', '{"topic": "governing_law"}', 1, 20);
INSERT INTO tool_calls VALUES (37, 1055, 1, 'lookup_playbook', '{"topic": "other"}', 1, 42);
INSERT INTO tool_calls VALUES (38, 1064, 1, 'lookup_playbook', '{"topic": "liability_cap"}', 1, 17);
